hugo_env: &hugo_env
   BASE_URL: https://${DRONE_REPO_OWNER,,}.github.io/${DRONE_REPO_NAME}/

kind: pipeline
type: docker
name: hugo-website
steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env
    commands:
      - hugo --baseURL $BASE_URL

  - name: deploy-to-s3
    image: amazon/aws-cli:latest
    commands:
      - aws s3 sync public/ s3://resto-files-ccm2 --delete
      - aws s3 cp s3://resto-files-ccm2/index.html s3://resto-files-ccm2/index.html --cache-control "no-cache"
