---
hugo_env: &hugo_env
   BASE_URL: https://resto-drone-ccm2.s3.us-east-1.amazonaws.com/

kind: pipeline
name: hugo-s3-deploy
steps:
  - name: hugo-build
    image: klakegg/hugo:0.120.0-ext-alpine
    environment:
      <<: *hugo_env
    commands:
      - hugo --minify --baseURL $BASE_URL

  - name: deploy-to-s3
    image: plugins/s3
    settings:
      bucket: resto-files-ccm2
      region: us-east-1
      source: public/
      target: /
      delete: true
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
    when:
      event: push
      branch: master

  - name: display_urls
    image: lowess/drone-tabulate
    environment:
      <<: *hugo_env
    settings:
      headers:
        - Service
        - URL
      rows:
        -
          - "S3 Website"
          - https://resto-drone-ccm2.s3-website-us-east-1.amazonaws.com/
        -
          - "S3 Direct"
          - https://resto-drone-ccm2.s3.us-east-1.amazonaws.com/
    when:
      event: push
      branch: master
